---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: proxy
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - www.bankofamerica.com
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: splicing-without-connect
spec:
  hosts:
  - www.bankofamerica.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: splicing-without-connect
spec:
  hosts:
  - www.bankofamerica.com
  gateways:
  - proxy
  tls:
  - match:
    - gateways:
      - proxy
      port: 443
      sniHosts:
      - www.bankofamerica.com
    route:
    - destination:
        host: www.bankofamerica.com
        port:
          number: 443
