# Envoy + BoringSSL + ICX crypto multibuffer
# Requires: Icelake CPU
# Applies: Istio ingress gateway and sidecars
# Feature: TLS handshale acceleration using Icelake crypto multibuffers (avx512)

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  tag: 1.12.0
  meshConfig:
  # Enable for envoy debugging
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyStatsMatcher:
        inclusionPrefixes:
          - "listener"

  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        overlays:
          - kind: Deployment
            name: istio-ingressgateway
            patches:
            - path: spec.template.spec.containers.[name:istio-proxy].args.[-1]
              value: "--concurrency=4"
        # Limit CPU/MEM usage to 4 vCPUs/4 GB fo QoS reasons.
        # Enable CPU manager static policy in kubelet to even more deterministic results.
        resources:
          requests:
            cpu: 4000m
            memory: 4096Mi
          limits:
            cpu: 4000m
            memory: 4096Mi
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
    pilot:
      k8s:
        env:
        - name: PRIVATE_KEY_PROVIDER
          value: "cryptomb" # this controls the SDS service which configures gateways

  values:
    # Annotate pods with
    #     inject.istio.io/templates: sidecar,cryptomb
    #
    # Note: CryptoMB doesn't have any method for guiding the workload to
    # an AVX-512 enabled node, so when you annotate the pod with the
    # cryptomb annotation, also set the taints correctly.
    sidecarInjectorWebhook:
      templates:
        cryptomb: |
          spec:
            containers:
            - name: istio-proxy
              env:
              - name: PRIVATE_KEY_PROVIDER
                value: cryptomb # needed for proxy-agent
    pilot:
      image: registry.fi.intel.com/staging/pilot:latest
    global:
      proxy:
        image: registry.fi.intel.com/staging/proxyv2:latest
    telemetry:
      enabled: false
