---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rule-configmap
data:
  index.html: |
         SecRuleEngine On
         SecRule ARGS:param1 "test" "id:1,phase:1,log,status:200,msg:'Test rule'"
         SecRule ARGS:param1 "attack" "id:2,phase:1,deny,status:400,msg:'Test rule'"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: msrules
  replicas: 2 
  template:
    metadata:
      labels:
        app: msrules
    spec:
      containers:
      - name: rules
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: rules-service
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: rules-service
        configMap:
          name: rule-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: rule-service
  namespace: default
spec:
  selector:
    app: msrules
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
      targetPort: 80

