# Envoy + OpenSSL + ICX crypto multibuffer
# Requires: Icelake CPU
# Applies: Istio ingress gateway and sidecars
# Feature: TLS handshale acceleration using Icelake crypto multibuffers (avx512)

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  tag: 1.9.4
  # Enable for envoy debugging
  #  meshConfig:
  #    accessLogFile: /dev/stdout
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
        - name: OPENSSL_CONF
          value: "/etc/ssl/openssl-avx512.cnf"
  values:
    global:
      proxy:
        image: registry.fi.intel.com/istio-intel/proxyv2-openssl:1.9.4
